### ISSUE TITLE
Motor Guide fails to return a valid response

### ISSUE THREAD

**Issue by danhorst** [JohnCoker/thrustcurve3#11]
[Cross post from TRF](https://www.rocketryforum.com/threads/is-the-thrustcurve-org-website-down.161266/page-3#post-2036329)

Using the Motor Guide ("Match a Rocket", https://www.thrustcurve.org/motors/guide.html):

Windows 10 Enterprise version 1903/Chrome 84.0.4147.135 (Official Build) (64-bit) (cohort: Stable) gives a 403 unauthorized when viewing a result page e.g. https://www.thrustcurve.org/motors/guide/5f43fb261d1d4400045ce914/summary.html

Same for Android 10 build QQ3A.200805.001/Chrome 84.0.4147.125

Windows 10 Enterprise version 1903/Firefox 78.0.2 just loads a blank page
Same for Android 10 build QQ3A.200805.001/Firefox Nightly 200823

Form data from Win10/Firefox 78:

```
bodyDiameter=42
bodyDiameterUnit=mm
weight=400
weightUnit=g
mmtDiameter=38
mmtDiameterUnit=mm
mmtLength=300
mmtLengthUnit=mm
cd=0.6
guideLength=1
guideLengthUnit=m
class=I
type=reload
manufacturer
```

Request payload:
```
bodyDiameter=42&bodyDiameterUnit=mm&weight=400&weightUnit=g&mmtDiameter=38&mmtDiameterUnit=mm&mmtLength=300&mmtLengthUnit=mm&cd=0.6&guideLength=1&guideLengthUnit=m&class=I&type=reload&manufacturer=
```
Firefox receives no response from the resulting summary page:
https://www.thrustcurve.org/motors/guide/5f43fa721d1d4400045ce8c9/summary.html

I suspect that Chrome is interpreting the same null response as a 403.

**Comment by JohnCoker** [comment]
Thanks. I fixed it. (Viewing the motor guide failed if you were not logged
in.)

John

**Comment by danhorst** [comment]
Looks good! Thanks!
