### ISSUE TITLE
Endpoint for getting motor data by motorId

### ISSUE THREAD

**Issue by broofa** [JohnCoker/thrustcurve3#23]
It'd be nice to have a way to fetch motor data by `motorId`.  Currently this does not appear to be possible.

For example, http://www.thrustcurve.org/api/v1/search.json?motorId=5f4294d20002310000000402 returns all 1,095 motors currently in the database. :-/

This would be useful for two reasons:
1. Clients that only need a subset of motor data most of the time would not have to cache the full set of data.
2. Clients that need to update their cached version of data for a given motor (in the event it changes... not that I expect that happens very often.)

Add this to the list in #18, I guess?

**Comment by JohnCoker** [comment]
1. It sounds like a bug that all motors get returned if invalid criteria are specified.
 2. Adding ID as a criterion would be fine. (I hadn't anticipated that would keep the ID, but it seems reasonable.)
