### ISSUE TITLE
Inconsistent commonName vs. designation for SCR motors

### ISSUE THREAD

**Issue by broofa** [JohnCoker/thrustcurve3#50]
The following SCR motors have significantly different [average] thrusts mentioned in the `commonName` vs in the `designation`:
```
SCR A3  .vs.  SCR-A8
SCR B4  .vs.  SCR-B6
SCR C3  .vs.  SCR-C6
```

This is a little confusing.  For example, it's a little odd that the SCR-A8 shows up in[ these search results](https://www.thrustcurve.org/motors/search.html?availability=all&text=a3) (for "A3")

**Comment by JohnCoker** [comment]
I updated the common name fields. This appears to have been done intentionally as there was an alternate name with the more obvious value, but I simplified all three motor entires.

Note that this repo is for the software itself. I would like to keep data issues separate. If you find bad info, there is a link to report it on the site itself.
